################ German language ##################
[de]
languageName = "DE"
languageCode = "de-de"
[de.params]
  reading_speed = 178
weight = 1

################ English language ##################
[en]
languageName = "EN"
languageCode = "en-us"
[en.params]
  reading_speed = 178
weight = 2
