############# English navigation ##############
########### SOLUTIONS ###########
# main
[[main]]
identifier = "solution"
name = "Lösungen"
url = "/solutions"
weight = 10

[[main]]
identifier = "solution-1"
name = "Sicherheits-Kultur"
url = "/solutions/security-culture"
weight = 10
post = "Das Un[be]greifbare Geheimnis sicherer und wiederstandsfähiger Organismen"
parent = "solution"

[[main]]
identifier = "solution-2"
name = "sSDLC"
url = "/solutions/ssdlc"
weight = 20
post = "Der sichere Software-Entwicklungs-Lebenszyklus"
parent = "solution"

########### FORMATS ###########
[[main]]
identifier = "formats"
name = "Formate"
url = "/formats"
weight = 15

[[main]]
identifier = "formats-workshop"
name = "Workshops"
url = "/formats/index.html#workshops"
weight = 10
post = "Workshops für mehr Lebendigkeit und Intensive Zusammenarbeit"
parent = "formats"

[[main]]
identifier = "formats-trainings"
name = "Trainings"
url = "/formats/index.html#trainings"
weight = 20
post = "Trainings schulen und verbinden"
parent = "formats"

[[main]]
identifier = "formats-talk"
name = "Talk"
url = "/formats/index.html#talks"
weight = 30
post = "Talks für events oder Security Champions"
parent = "formats"

########### BLOG ###########
[[main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[main]]
identifier = "blog-posts"
name = "Posts"
url = "/blog/index.html"
weight = 1
post = "Alle Posts des Blogs"
parent = "blog"

[[main]]
identifier = "blog-categories"
name = "Kategorien"
url = "/categories/index.html"
weight = 10
post = "Navigation nach Kategorien"
parent = "blog"

[[main]]
identifier = "blog-tags"
name = "Tags"
url = "/tags/index.html"
weight = 20
post = "Navigation nach Tags"
parent = "blog"

########### ABOUT ###########
[[main]]
identifier = "about"
name = "Über"
url = "/about/"
weight = 30

[[main]]
identifier = "about-me"
name = "Me"
url = "/about"
weight = 1
post = "Die ganze Geschichte"
parent = "about"

[[main]]
identifier = "about-mission"
name = "Meine Motivation"
url = "/about/index.html#mission"
weight = 10
post = "Geschichte"
parent = "about"

[[main]]
identifier = "about-experience"
name = "Meine Erfahrung"
url = "/about/index.html#experience"
weight = 20
post = "verschiedene Erfahrungen"
parent = "about"

[[main]]
identifier = "about-interest"
name = "Meine Interessen"
url = "/about/index.html#interest"
weight = 25
post = "verschiedene Interessen"
parent = "about"

[[main]]
identifier = "about-certificates"
name = "Meine Zertifikate"
url = "/about/index.html#certificates"
weight = 30
post = "verschiedene Zertifizierungen"
parent = "about"

[[main]]
identifier = "about-cv"
name = "Mein Lebenslauf"
url = "/about/index.html#certificates"
weight = 40
post = "Lebenslauf zum Download"
parent = "about"

########################################################
# footer menu
[[footer]]
name = "Solutions"
url = "/solutions/"
weight = 10

[[footer]]
name = "About"
url = "/about/"
weight = 20

[[footer]]
name = "Impressum"
url = "/imprint"
weight = 30

[[footer]]
name = "Datenschutz"
url = "/privacy-policy"
weight = 40

[[footer]]
name = "Themen-Elemente"
url = "/elements"
weight = 50
